name: CI Build

on:
  push:
    branches:
      - main
      - 'feature/*'  # Add any other branches you want to include
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.4'

    - name: Get dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test  ./aznamingtool -coverprofile=coverage.out
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.out

    - name: Generate HTML coverage report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v2
      with:
        name: html-coverage-report
        path: coverage.html